### ISSUE TITLE
Unable to write to stream: fwrite(): SSL operation Failed with code 1. OpenSSL Error messages: error:1420C0CF:SSL routines:ssl_write_internal:protocol is shutdown

### ISSUE THREAD

**Issue by jakaprata** [romainrg/ratchet_client#10]
Hi guys, I got this error sometimes when sending messages from client, no solution yet,  I couldn't found where this error come from, because didn't  happen every time.

Unable to write to stream: fwrite(): SSL operation failed with code 1. OpenSSL Error messages:
error:1420C0CF:SSL routines:ssl_write_internal:protocol is shutdown

**Comment by milanpasic92** [comment]
Hi I got the same error. It appears to happen randomly after some time (and only for some clients). Not sure if it has something to do with client closing the connection from the other side or is related to file descriptor limits somehow.
